---
version: '3'
tasks:
  build:
    label: "Build {{.JSONNET_SOURCE}}"
    desc: "Build {{.JSONNET_SOURCE}} using Jsonnet"
    vars:
      JSONNET_SOURCE: example.jsonnet
    sources:
    - example.jsonnet
    - lib/*.libsonnet
    generates:
    - "*.plist"
    cmds:
    - > 
      jsonnet {{ .JSONNET_INCLUDE_DIRS | default "-J ." }} \
              -S \
              -m {{.JSONNET_BUILD_DIR | default "." }} \
              {{.JSONNET_SOURCE}} {{ if .JSONNET_EXTRAS }}{{ .JSONNET_EXTRAS }}{{ end }} {{ if .CLI_ARGS }}{{ .CLI_ARGS }}{{ end }}
  clean:
    cmds:
    - "{{ if .GENERATED_FILES }}rm -rf {{ .GENERATED_FILES | join ' ' }}{{ else }}echo 'nothing to clean'{{end}}"
    vars:
      GENERATED_FILES:
      - "*.plist"
  default:
    cmds:
    - task: build
